
import os
Import('env')

env.Append(
  CPPPATH = [
    "/usr/include/python2.6",
    "../src/",
  ],
  SWIGFLAGS=Split("-c++ -python -Isrc/"),

### workaround for scons bug
  #LDMODULEPREFIX="_",
  #LDMODULESUFFIX=".so",
  #SHLIBPREFIX="_",
  #SHLIBSUFFIX=".so",
  #SHLIBPREFIX="",
  #SHLIBSUFFIX="",
)
### actual workaround for scons bug
env['LIBPREFIX']=""


# the \# means "top level directory"
env.SharedLibrary(
  target = '_monowav.so',
  source = ['monowav.i', '../src/monowav.cpp'],
)

artifastring_lib_files = map(lambda(x): '..'+os.sep+'src'+os.sep+x,
	env['artifastring_lib_files'])

env.SharedLibrary(
  target = '_violin_instrument.so',
  source = ['violin_instrument.i'] + artifastring_lib_files,
)

# TODO: hard-coded python version again!
env.Install('$PREFIX/lib/python2.6/site-packages/', [
  '_monowav.so',
  'monowav.py',
  '_violin_instrument.so',
  'violin_instrument.py'
])

